name: cs510_latest
channels:
  - conda-forge
  - defaults
dependencies:
  - apscheduler=3.9.0
  - arpack=3.7.0
  - beautifulsoup4=4.12.2
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - catalogue=2.0.8
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - click=7.1.2
  - colorama=0.4.6
  - cryptography=40.0.2
  - cymem=2.0.7
  - cython-blis=0.7.9
  - dataclasses=0.8
  - flask=2.0.3
  - flask-apscheduler=1.12.4
  - glpk=4.65
  - gmp=6.2.1
  - gunicorn=20.1.0
  - icu=72.1
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsqlite=3.40.0
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.2
  - markupsafe=2.1.2
  - metis=5.1.0
  - mpfr=4.2.0
  - murmurhash=1.0.9
  - ncurses=6.3
  - numexpr=2.8.4
  - numpy=1.24.3
  - openssl=3.1.0
  - packaging=23.1
  - pandas=1.5.3
  - pathy=0.10.1
  - pip=23.1.2
  - preshed=3.0.8
  - pycparser=2.21
  - pydantic=1.7.3
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-igraph=0.9.1
  - python_abi=3.9
  - pytz=2022.7
  - readline=8.2
  - setuptools=67.7.2
  - shellingham=1.5.1
  - six=1.16.0
  - smart_open=5.2.1
  - soupsieve=2.4
  - spacy=3.0.5
  - spacy-legacy=3.0.12
  - srsly=2.4.6
  - suitesparse=5.10.1
  - tbb=2021.9.0
  - texttable=1.6.7
  - thinc=8.0.3
  - tk=8.6.12
  - tqdm=4.65.0
  - typer=0.3.2
  - tzdata=2023c
  - tzlocal=2.1
  - urllib3=1.26.15
  - wasabi=0.10.1
  - werkzeug=2.2.3
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - chardet==4.0.0
      - contourpy==1.0.7
      - cso-classifier==3.0
      - curlify==2.2.1
      - cycler==0.11.0
      - en-core-web-sm==3.0.0
      - fonttools==4.39.3
      - gensim==3.8.1
      - hurry-filesize==0.9
      - idna==2.10
      - importlib-resources==5.12.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - kneed==0.3.1
      - matplotlib==3.7.1
      - nltk==3.6.2
      - pillow==9.5.0
      - pyparsing==3.0.9
      - python-levenshtein==0.12.2
      - regex==2023.3.23
      - requests==2.25.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - strsimpy==0.2.0
      - threadpoolctl==3.1.0
      - update-checker==0.18.0
      - zipp==3.15.0
